krakend/krakend-documentation

throttling/rate-limit.md
Adding three back-ticks at the beginning of the "Router rate limit example" code block fixed JSON formatting.
=> Fix code block formatting

endpoints/debug-endpoint.md, endpoints/parameter-forwarding.md, endpoints/sequential-proxy.md, overview/introduction.md
Documentation is not clear enough.
Expanding the parameter forwarding document and adding how to test it.
=> Better querystring documentation and /__debug endpoint

endpoints/parameter-forwarding.md
Docs for
```
"querystring_params":[  
"*"
],
```
=> Add all query string parameters forwarding

logging-metrics-tracing/opencensus.md, logging-metrics-tracing/prometheus.md
Update of the documentation based on @jrasell PR:
https://github.com/devopsfaith/krakend-opencensus/pull/24
=> Allow prometheus exporter namespace to be configurable.

endpoints/security.md
as reported at https://github.com/devopsfaith/krakend-httpsecure/issues/1 the example was wrong
=> sts_seconds example fixed

logging-metrics-tracing/logging.md
- fix missing comma in logstash config json example
- remove multiple unused whitespaces
- and also apply 2 space indentation
=> fix json typo

README.md
just added the protocol, as the previos version thought it was a directory
=> Fixing hugo link

backends/overview.md
The second element in the `host` for the first backend was missing a trailing comma
=> Properly delimit elements in the host array

overview/installing.md, overview/verifying-packages.md
repo.krakend.io is now served using https
=> Serve the repository under HTTPS #91

backends/lambda.md
function param name first character is uppercased
see https://github.com/devopsfaith/krakend-ce/issues/247
=> Lambda function param fixed

backends/martian.md
this PR removes an example of a modifier not included in the project (as reported at https://github.com/devopsfaith/krakend/issues/423)
=> querystring modifier removed

endpoints/parameter-forwarding.md
The channel should be iOS instead of "foo", as specified in the URL
=> Fixed mandatory+optional query string example

authorization/jwt-validation.md
With 1.3.0, scopes declared as string struct. But if you follow this doc which is ``scopes (string): List of scopes to validate, separated by a space.``, you are gonna get ``json: cannot unmarshal string into Go struct field SignatureConfig.scopes of type []string`` error. So this statement is misleading. That's why I changed it.
https://github.com/devopsfaith/krakend-jose/blob/f02ca595b00459c442f5f8a18891b1c113386db9/jws.go#L39
=> scopes description changed string to list.

endpoints/lua.md
The JSON format does not allow commas at the end one field object.
=> Fix wrong JSON example syntax

authorization/jwt-validation.md
The name of the "propagate-claims" setting was incorrectly "propagate-claim" in the list, even though it showed up correctly in the code example on line 283.
=> Fix propagate-claims name

configuration/flexible-config.md
Fix minor typo (`insidde` to `inside`) in flexible-config documentation.
=> Fix minor typo in flexible-config documentation

telemetry/prometheus.md
The port in the opencensus config is the one on which _the exporter_ will listen.
Prometheus _pulls_ the exposed data.
=> docs: clarify Prometheus port

extending/plugin-modifiers.md
I noticed there was a missing line in the documentation when creating a plugin. I added the line so it will be easier for others to follow the example.
=> Added missing line in code examples for plugin

configuration/flexible-config.md
The example command was not reflecting with the given hypothetical folder structure
=> Fix FC_SETTINGS in usage example

backends/data-manipulation.md
`Reponse` should be `Response`
=> Fix Typo on data manipulation documentation

endpoints/lua.md
Signed-off-by: Atul Krishna <atultherajput@gmail.com>
There was a typo error in `lua.md` file.
=> Fixed typo in lua.md

developer/integration-tests.md
the pkg name should point to the v2 version
=> fix install instructions for the integration cmd

backends/pubsub.md
According to my experience trying to get an SQS connection to work, there should only be one protocol in this string.
=> Fix AWS SQS host example

deploying/kubernetes.md
Mikescandy's repository at https://github.com/mikescandy/krakend-helm is not updated often (last update December 14, 2021) and uses the `latest` tag for the krakend image. There are 12 commits total here by 3 contributors.
The repo at https://github.com/equinixmetal-helm/krakend uses explicit version numbers and has regular releases and a full CI/CD pipeline set up vis GitHub Actions here: https://github.com/equinixmetal-helm/krakend/actions and the latest commit from 5 days ago.
Compare this https://github.com/mikescandy/krakend-helm/pulse/monthly with https://github.com/equinixmetal-helm/krakend/pulse/monthly
=> Revise helm chart's Github link to active repo

endpoints/common-expression-language-cel.md
Greetings! 
This PR is the result of a question that popped up on Slack yesterday. It tweaks documentation for CEL syntax regarding multi-value query string parameters and adds an example that checks for a value in the array via CEL. It assumes array query string parameters follow the form `?foo[]=bar&foo[]=baz` but also includes a note on how to handle the `?foo=bar&foo=baz` use case. 
Let me know what you think. I'm happy to change it up if you need it. Thanks!
=> Add an array query string parameter example

service-settings/CORS.md
There were two missing end braces in the CORS documentation. It can be a bit confusing if one copies and pastes the code, and it has errors.
=> Add missing braces in CORS.md

developer/hot-reload.md
I think most people trying to build the Docker image will know what to do, but here is a PR just in case :)
=> Doc:Community edition 2.9.4 --  context missing from instructions

backends/martian.md
The header.Id modifier supports an undocumented parameter that allows you to rename the default header from "X-Krakend-Id" to something else.
This pull request also requires adding this "header" parameter to the schema.
{{< schema data="modifier/martian.json" property="header.Id" >}}
=> header.Id name override undocumented parameter

ai-gateway/security.md
Summary
- Fix broken internal link to AI Gateway governance section by correcting the path from /docs/ai-gateway/governance/ to /docs/enterprise/ai-gateway/governance/
- Add Enterprise badge to indicate this feature is only available in KrakenD Enterprise Edition
=> Fix incorrect link to ai governance section
