faq.md
document how the status codes are handled by the KrakenD
=> status codes

overview/configuration.md, overview/introduction.md
Flexible configuration needs an example
=> Explain configuration file structure

service-discovery/dns-srv.md, service-discovery/etcd.md, service-discovery/overview.md
=> `disable_host_sanitize` param added to the examples

endpoints/sequential-proxy.md, endpoints/static-proxy.md
=> Add static proxy documentation

service-settings/TLS.md
This entry requires updating the `config.toml` as it adds a new leaf in the menu
=> Add TLS #20

endpoints/lua.md
- Corrected the namespace names to use and explained where they are used.
- Listed the sequence of processing for the different sections.
- Added two examples.
=> Corrected the namespace names, add examples

authorization/client-credentials.md
the json modifier does not affect the request to the token issuer
=> misleading statement removed

endpoints/lua.md
https://github.com/devopsfaith/krakend/issues/328
=> lua.md fixed

authorization/jwt-overview.md, authorization/jwt-signing.md, authorization/jwt-validation.md, authorization/revoking-tokens.md
- Explained that `kid` header is necessary and given details around it.
- Explained the validation process
- Extended the signing documentation with graphs and code examples
=> #27 JWT needs more explanation

authorization/jwt-validation.md
=> JWT validation

backends/amqp.md
amqp request params should be uppercased
=> Fix amqp producer example

endpoints/common-expression-language-cel.md
Incorrect variable description fixed.
https://github.com/devopsfaith/krakend-cel/blob/master/internal/cel.go#L135
=> common-expression-language-cel.md fixed

backends/circuit-breaker.md
- Added the `name` in the example code block
- Explained all attributes
- Moved the section "how it works" to the end of the document
- Removed aliases from pages that changed the url in 2016 😂
=> Circuit Breaker accepts a name #90

endpoints/lua.md
use the body getter instead of the body setter
=> fix lua example

endpoints/_index.md
I was fixing a highlighting error. There was a backtick missing.
=> [Typo] Update Documentation -> _index.md

backends/martian.md
and also, querystring added to the list of loaded pkgs
=> links fixed

backends/_index.md
Because of https://github.com/krakendio/krakend-ce/issues/519 I want to make it slightly more explicit about the consequences of setting host stanitization for non http hosts.
=> Update part of documentation about host sanitization

deploying/_index.md
=> docs(deploying): fix typo

authorization/revoking-tokens.md
This just adds a small paragraph. #188 
I'm open to any suggestions. Just wanting to save the next person some time when they come across this behavior themselves 🤗
=> Added note describing required bloom filter client format

logging/logstash.md
Just change the link to English version instead of the Spanish one.
=> Use English version of logstash link at logstash.md

authorization/keycloak.md
just a minor fix to document the correct jwks endpoint.
=> fix keycloak's JWKS endpoint

v1.4/service-discovery/dns-srv.md
=>  Fix date on public doc

endpoints/parameter-forwarding.md, v2.9/endpoints/common-expression-language-cel.md
=> Misdocumented behaviour with input_headers config and content-type #258
